server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  port: 8081
spring:
  # 코드 변경시 재부팅
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # DB 접속 정보 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project-db-campus.smhrd.com:3307/BIG_news_23?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: BIG_news_23
    password: news1
  data:
    mongodb:
      uri:  mongodb://bignews:news@43.201.59.116:27017/newsummary?authSource=admin&authMechanism=SCRAM-SHA-1
      # uri : mongodb://bignews:news@43.201.59.116:27017/?authMechanism=DEFAULT
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         format_sql:true #sql 보기 편하게 해줌
#         show-sql: true
cloud:
  aws:
    credentials:
      accessKey: AKIATNUJUUJBDTFVJD6D
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: newsummary-bucket
logging.level:  #띄어쓰기 없음
  '[org.hibernate.SQL]': debug   
logging:
  level:
    org:
      springframework:
        security: DEBUG