server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  port: 8081

spring:
  profiles:
    include:
      - aws
      - credentials
  # 코드 변경시 재부팅
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # DB 접속 정보 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project-db-campus.smhrd.com:3307/BIG_news_23?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: BIG_news_23
    password: news1
  data:
    mongodb:
      uri:  mongodb://bignews:news@43.201.59.116:27017/newsummary?authSource=admin&authMechanism=SCRAM-SHA-1
  # 파일 최대 업로드 용량 지정
  servlet:
    multipart:
      enabled: true
      maxFileSize: 20MB
      maxRequestSize: 20MB
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         format_sql:true #sql 보기 편하게 해줌
#         show-sql: true

logging.level:  #띄어쓰기 없음
  '[org.hibernate.SQL]': debug   
logging:
  level:
    org:
      springframework:
        security: DEBUG